import type { MarketTab, ScannerStock } from "@/types/stock";

/** Placeholder rows until API routes / external feeds are wired. */
export function getMockScannerRows(market: MarketTab): ScannerStock[] {
  const domestic: ScannerStock[] = [
    {
      symbol: "005930",
      name: "삼성전자",
      market: "domestic",
      price: 71200,
      changePercent: 1.24,
      signals: ["ma_cross", "rsi"],
      signalSummary: "단기 이평선 상향 돌파, RSI 과매도 구간 탈출",
    },
    {
      symbol: "000660",
      name: "SK하이닉스",
      market: "domestic",
      price: 198500,
      changePercent: -0.82,
      signals: ["bollinger", "volume"],
      signalSummary: "볼린저 하단 반등, 거래량 급증",
    },
    {
      symbol: "035420",
      name: "NAVER",
      market: "domestic",
      price: 201000,
      changePercent: 0.45,
      signals: ["rsi", "macd"],
      signalSummary: "RSI 중립대 상단, MACD 히스토그램 개선",
    },
    {
      symbol: "035720",
      name: "카카오",
      market: "domestic",
      price: 48550,
      changePercent: 2.1,
      signals: ["ma_cross", "bollinger"],
      signalSummary: "20일선 지지 후 반등, 밴드 수축 후 확장",
    },
    {
      symbol: "005380",
      name: "현대차",
      market: "domestic",
      price: 228500,
      changePercent: -0.35,
      signals: ["volume", "macd"],
      signalSummary: "기관 매수 유입, MACD 골든크로스 근접",
    },
    {
      symbol: "006400",
      name: "삼성SDI",
      market: "domestic",
      price: 412000,
      changePercent: 0.91,
      signals: ["rsi", "bollinger"],
      signalSummary: "RSI 다이버전스, 밴드 중심선 회복",
    },
    {
      symbol: "051910",
      name: "LG화학",
      market: "domestic",
      price: 298000,
      changePercent: -1.05,
      signals: ["ma_cross"],
      signalSummary: "60일선 저항 돌파 시도",
    },
    {
      symbol: "068270",
      name: "셀트리온",
      market: "domestic",
      price: 178900,
      changePercent: 0.62,
      signals: ["macd", "volume"],
      signalSummary: "MACD 상향 교차, 거래량 동반",
    },
    {
      symbol: "207940",
      name: "삼성바이오로직스",
      market: "domestic",
      price: 845000,
      changePercent: 0.18,
      signals: ["rsi", "ma_cross"],
      signalSummary: "RSI 50선 회복, 장기 이평선 정배열",
    },
    {
      symbol: "012330",
      name: "현대모비스",
      market: "domestic",
      price: 251500,
      changePercent: -0.74,
      signals: ["bollinger", "macd"],
      signalSummary: "밴드 하단 지지, MACD 모멘텀 약화",
    },
  ];

  const us: ScannerStock[] = [
    {
      symbol: "AAPL",
      name: "Apple Inc.",
      market: "us",
      price: 198.42,
      changePercent: 0.67,
      signals: ["ma_cross", "rsi"],
      signalSummary: "50일선 상회, RSI 과열 구간 근접",
    },
    {
      symbol: "MSFT",
      name: "Microsoft",
      market: "us",
      price: 428.9,
      changePercent: -0.21,
      signals: ["bollinger", "volume"],
      signalSummary: "밴드 중심선 부근, 거래량 평균 이하",
    },
    {
      symbol: "NVDA",
      name: "NVIDIA",
      market: "us",
      price: 121.35,
      changePercent: 2.45,
      signals: ["macd", "ma_cross"],
      signalSummary: "MACD 강세, 단·중기 이평 정배열",
    },
    {
      symbol: "AMZN",
      name: "Amazon",
      market: "us",
      price: 189.12,
      changePercent: 0.88,
      signals: ["rsi", "bollinger"],
      signalSummary: "RSI 상승 다이버전스, 밴드 상단 돌파",
    },
    {
      symbol: "GOOGL",
      name: "Alphabet A",
      market: "us",
      price: 176.2,
      changePercent: -0.55,
      signals: ["volume", "macd"],
      signalSummary: "거래량 증가, MACD 히스토그램 축소",
    },
    {
      symbol: "META",
      name: "Meta Platforms",
      market: "us",
      price: 512.4,
      changePercent: 1.02,
      signals: ["ma_cross", "bollinger"],
      signalSummary: "20일선 지지, 밴드 폭 확대",
    },
    {
      symbol: "TSLA",
      name: "Tesla",
      market: "us",
      price: 248.5,
      changePercent: -1.8,
      signals: ["rsi", "macd"],
      signalSummary: "RSI 약세권, MACD 데드크로스",
    },
    {
      symbol: "JPM",
      name: "JPMorgan Chase",
      market: "us",
      price: 198.75,
      changePercent: 0.34,
      signals: ["ma_cross"],
      signalSummary: "200일선 상방 유지",
    },
    {
      symbol: "V",
      name: "Visa",
      market: "us",
      price: 278.1,
      changePercent: 0.12,
      signals: ["bollinger", "volume"],
      signalSummary: "밴드 내 횡보, 거래량 안정",
    },
    {
      symbol: "JNJ",
      name: "Johnson & Johnson",
      market: "us",
      price: 152.3,
      changePercent: -0.41,
      signals: ["rsi", "ma_cross"],
      signalSummary: "RSI 중립, 장기 이평 수렴",
    },
  ];

  return market === "domestic" ? domestic : us;
}
